### ISSUE TITLE
Project Code Improvements & Suggestions.

### ISSUE THREAD

**Issue by divyanshu-rawat** [mercedes-benz/product-kit_react#10]
Hi,

First of all thanks for open-sourcing and creating this nice project.
I was looking into this project to contribute. 
I can highlight some points by having a brief look at the project I can contribute to if that’s fine with the team.

1. We don’t have TS support yet for the project.
2. We don’t have many test cases written here yet.
3. Most of the components are class-based we can move them to functional components and write some custom hooks to re-use the logic.
4. We can also do some cleanup and remove unused variables, and imports.

Please let me know what you think!
Cheers
Divy

**Comment by divyanshu-rawat** [comment]
Hi @stenanderssen,

To be honest, I still don’t know how I plan to use this project, for me I consider it an opportunity to contribute back to Open source. My suggestions are based on the whole project not the individual parts of it. 

Nevertheless, In case the development is on hold I might consider contributing to any other project here how about https://github.com/mercedes-benz/product-kit_vue.
thanks!

Looking forward to your reply!
Divy

**Comment by stenanderssen** [comment]
Hi Divy,

All "Product Kit" repositories are currently on hold and in maintenance mode ;) If you want to contribute to an open source project from Mercedes-Benz please have a look at the following projects, they are all currently looking for active contribution:

- https://github.com/mercedes-benz/sechub
- https://github.com/mercedes-benz/mo360-ftk
- https://github.com/mercedes-benz/DnA

 I will close this issue as resolved. If you have any further questions feel free to comment to this issue anyway.

Kind regards
Sten

**Comment by divyanshu-rawat** [comment]
Perfect I will look into the above projects then thanks!
